
[build-system]
requires = [
    "setuptools",
    "numpy>=2",
]
build-backend = "setuptools.build_meta"

[project]
name = "jmod"
dynamic = ["version"]

# to try
#[tool.setuptools]
#ext-modules = [
#  {name = "j1", sources = ["jmod.c", "jbit.c"]}
#]
